[project]
name = "soscleanai"
version = "0.1.0"
description = "Project to experiment using AI to clean up sos reports"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymilvus>=2.6.2",
]
